# Generated by Django 5.0.1 on 2024-02-07 19:15

import autoslug.fields
from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_description', CKEditor5Field('Text', config_name='extends')),
                ('blog_image', models.ImageField(default=None, max_length=350, upload_to='media')),
                ('blog_tag', models.CharField(blank=True, default='View', max_length=50, null=True)),
                ('blog_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='product_title', unique=True)),
            ],
        ),
    ]
