# Generated by Django 5.0.1 on 2024-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_tag',
            field=models.CharField(blank=True, default='Blog', max_length=50, null=True),
        ),
    ]
